### ISSUE TITLE
Confusion on Evaluation Metrics

### ISSUE THREAD

**Issue by wang802** [truthless11/HRL-RE#10]
Nice work on dealing with overlapped RE problem, but i still have some confuse. In your calc_acc function, u only consider begin of source/target entity(4 and 5), but in your paper P5 Evaluation  Metrics part, "A triplet is regarded as correct if the relation type and the two corresponding entities are all correct." I wonder whether there's some detail i missed in the paper.Could u explain that for me?Thank u.

**Comment by truthless11** [comment]
In the implementation of evaluation metrics, we only judge the head of the entity following the existing studies, which we do not mention it explicitly in the paper. You can refer to **SPTree**
> We treat an entity as correct when its type and the region of its head are correct. 

and **Tagging**.
> A triplet is regarded as correct when its relation type and the head offsets of two corresponding entities are both correct.

It should be noted that the tail of the entity is considered in **CopyR** instead.
>  When copying the entity, we only copy the last word of it.
