### ISSUE TITLE
where is train.json

### ISSUE THREAD

**Issue by junlei007** [truthless11/HRL-RE#11]
the train.json dont exist in the files download from the link 
`
(base) u@pc:~/HRL-RE/data/NYT10$ ls
filtered-freebase-simple-topic-dump-3cols.tsv  kb_manual             README.md
heldout_relations                              manual-05-06.tgz      relations.tar.gz
heldout_relations.tgz                          nyt-2005-2006.backup

`

**Comment by truthless11** [comment]
The preprocessed datasets that we used for relation extraction are provided in corresponding subdirectories under `HRL-RE/data`, and the link for the dataset is shown in the README. Here is the link: [NYT10](https://drive.google.com/open?id=1jt_yurHorliIor8uDqvirQlGyFYwW81c) and [NYT11](https://drive.google.com/open?id=1XRHj4a_aj-p96qCsnSKf3IfSnRM3UW3O)

**Comment by junlei007** [comment]
THX  I got it
