### ISSUE TITLE
have u compared with the “Robust Distant Supervision Relation Extraction via Deep Reinforcement Learning”？

### ISSUE THREAD

**Issue by dh12306** [truthless11/HRL-RE#13]
the code is here ：Panda0406/Reinforcement-Learning-Distant-Supervision-RE，I try to run both of urs，but did not success until now，so I  wonder  if u have done some test ，thx @truthless11

**Comment by truthless11** [comment]
We didn't compare with that paper because they are addressing "relation type classfication" rather than "relation fact extraction" here.
