### ISSUE TITLE
How to deal with the words with low frequency (only appearing one or two times)? 

### ISSUE THREAD

**Issue by WOWNICE** [truthless11/HRL-RE#15]
I split the NYT11 dataset by myself (90% for training, 10% for validation), and I want to construct the dictionary for future use. Here is what I did: 

- I don't want the word appearing in the entities to be replaced by the \<unk\> token, so the words in the entities go all into the dictionary. 
- I filter out the words with low frequency (appearing at least 3 times in the whole training set). 

**After filtering, 40,666 words are selected out of 83,399 words, which means half of the words will be replaced by \<unk\> token.** I feel this is not a very acceptable result while I don't know the traditional way of solving this problem of 'low frequency' in the Joint Extraction of Entities and Relations task. Am I doing it wrong? 

Then I found that there are some (654) of the words in the dictionary are not in the 'vector.txt' file, which contains 144,885 words. I'm wondering how you construct the dictionary for the NYT11 corpus. 

Any advice is appreciated. Thanks.

**Comment by truthless11** [comment]
This is a general NLP problem of how to build a vocabulary from datasets. There are many solutions to overcome the out-of-vocabulary issue that the word representation cannot handle unseen words or rare words well. Recently, some tokenizing techniques, which split the text into subwords, are applied in pre-trained language models, such as `Byte-Pair Encoding` and `WordPiece`. Please refer to these studies.
