### ISSUE TITLE
Relation indicator questions

### ISSUE THREAD

**Issue by SamsonYuBaiJian** [truthless11/HRL-RE#17]
Hi there @truthless11 , can I confirm with you two things regarding the relation indicators:

- A relation can be tagged to only one token at each time in the sequence, i.e. the relation indicator has no "inside", only one "beginning"
- There is no ground-truth label for the position of the relation, so for your accuracy/F1/top reward calculations, as long as the relation is inside the list of top_actions, regardless of position, you consider it a hit for the relation/top action

Thank you.

**Comment by truthless11** [comment]
The answers to the two questions are both yes.
