### ISSUE TITLE
Replace LSTM with Bert 

### ISSUE THREAD

**Issue by anshengluo** [truthless11/HRL-RE#4]
hi,

       thanks for  the work that you guys  have done.  I thinks it is useful  for me. By the way, Did you guys  think about replacing LSTM with Bert ?  I did that. Just for you know,  I think it's better than lstm  . 

original :

 epoch 0: dev F1: 0.5004633920296572, test F1: 0.4455146364494807
  2 epoch 0: dev F1: 0.5252709640616087, test F1: 0.4531946508172363
  3 epoch 1: dev F1: 0.6126023657870792, test F1: 0.5121126245543468
  4 epoch 2: dev F1: 0.65594573897823, test F1: 0.5601257532093266
  5 epoch 3: dev F1: 0.7098411297440423, test F1: 0.6034816247582204
  6 epoch 4: dev F1: 0.7194697225030896, test F1: 0.6027715690657129
  7 epoch 5: dev F1: 0.7338809497018117, test F1: 0.6199315191926474
  8 epoch 6: dev F1: 0.7422517750478981, test F1: 0.6272242796495349
  9 epoch 7: dev F1: 0.7402568145978825, test F1: 0.621670592498641
 10 epoch 8: dev F1: 0.7411869701026328, test F1: 0.6330103990756377
 11 epoch 9: dev F1: 0.7489399687569738, test F1: 0.6232657417289221
 12 epoch 10: dev F1: 0.7425932184296495, test F1: 0.6252486887321396
 13 epoch 11: dev F1: 0.7450980392156862, test F1: 0.6251227568967057
 14 epoch 12: dev F1: 0.7373334851417511, test F1: 0.6234788178241376

 replace lstm with Bert : 

epoch 0: dev F1: 0.6218990590248076, test F1: 0.6196589769307924
epoch 1: dev F1: 0.6512136453094249, test F1: 0.6552458185504308
epoch 2: dev F1: 0.7469775474956822, test F1: 0.7369901547116737
epoch 3: dev F1: 0.6816816816816816, test F1: 0.685594321703489
epoch 4: dev F1: 0.7550843790566855, test F1: 0.7470723651286157
epoch 5: dev F1: 0.7624784853700516, test F1: 0.7482357618526986
epoch 6: dev F1: 0.7304055473839042, test F1: 0.7266874756145143
epoch 7: dev F1: 0.7833407177669471, test F1: 0.7696565863659661
epoch 8: dev F1: 0.7689260563380282, test F1: 0.746217121966081
epoch 9: dev F1: 0.7817984832069339, test F1: 0.7576124218592458
epoch 10: dev F1: 0.7933634992458521, test F1: 0.770678950530743
epoch 11: dev F1: 0.7926086956521738, test F1: 0.7637494981934967
epoch 12: dev F1: 0.8042003937869174, test F1: 0.769355001514081

**Comment by truthless11** [comment]
We haven’t tried to replace LSTM with BERT since our work was done before the submission deadline of AAAI 19 while BERT was released after that. Also, we don’t want to put much emphasis on network designs. You can see in our paper that HRL outperforms other baselines only using a simple policy network, which shows the effectiveness of the proposed hierarchical framework. 

Anyway, the result is truly impressive! I should say it’s really beyond my expectation. Thank you for your report and we are pleased to see any improvement by adding other tricks on our hierarchical framework.

**Comment by anshengluo** [comment]
Oh,I see. In my opinion, hierarchical framework  is  really a great idea. thanks again .

**Comment by misaki-sysu** [comment]
> Oh,I see. In my opinion, hierarchical framework is really a great idea. thanks again .

@anshengluo 
Hi, I am trying to replace LSTM with BERT either, but I come across some problems.
On Each epoch of training, the train accuracy and test F1 stays at 0, all the top_actions after prediction like [4,0,0,0,0,...,0,0]. and I have no idea what's wrong with my code, would you mind sharing your code?

**Comment by cjm1044642385** [comment]
> Oh,I see. In my opinion, hierarchical framework is really a great idea. thanks again .

Excuse me,could you share with me your code about the bert with this program？

**Comment by dh12306** [comment]
@anshengluo  hi guy，will u please share with us ur code that  replaced lstm with bert ?
