### ISSUE TITLE
What does the "tags" mean in key "relations" of data?

### ISSUE THREAD

**Issue by ObKsEm** [truthless11/HRL-RE#8]
Hi, I'm trying to train a model with my own data. So I want to know the meaning of "tags", the list of numbers in data.

For example, a json in train data:

> {"sentext": "if we can figure out how to program thousands of cores on a chip , the future looks rosy , '' said david a. patterson , a university of california , berkeley computer scientist who is a co-author of one of the standard textbooks on microprocessor design . ''", "entities": ["california", "berkeley"], "relations": [{"rtext": "/location/location/contains", "em2": "berkeley", "em1": "california", "tags": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 0, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}]}

**Comment by ObKsEm** [comment]
Sry! I see it in README.md.

**Comment by bifeng** [comment]
@ObKsEm  Hi, Have you got the right train data format ? 
```
{"sentext": "if we can figure out how to program thousands of cores on a chip , the future looks rosy , '' said david a. patterson , a university of california , berkeley computer scientist who is a co-author of one of the standard textbooks on microprocessor design . ''",
"relations": {
 "rtext": "/location/location/contains",
 "em2": "berkeley",
 "em1": "california",
 "tags": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, S_B, 0, T_B, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]}]}
}
```
Is it right ?

**Comment by ObKsEm** [comment]
Hi, I have a new question about tags. 

> Each relational triple is formatted as follows:
rtext : relation type
em1 : source entity mention
em2 : target entity mention
tags : the proposed entity annotation scheme for the sentence
0 : $O$ non-entity
1 : $S_I$ inside of a source entity
2 : $T_I$ inside of a target entity
3 : $O_I$ inside of not-concerned entity
4 : $S_B$ begin of a source entity
5 : $T_B$ begin of a target entity
6 : $O_B$ begin of not-concerned entity

If an entity appears twice in a sentence, how should the entity unrelated to the triple be labeled？
0, 6, or (4 or 5)?

For example:

> Mike, CEO of Google, said, "I really like the culture of Google."


Here "Google" appears twice as an entity. Obviously the tags of the first "Google" is 5. But how should the second "Google" be labeled?

**Comment by truthless11** [comment]
In this case, the second "Google" should be labeled as 6.

**Comment by ObKsEm** [comment]
@truthless11 Thank you very much.
